version: '3.1'

services:
  mysql:
    # image: mysql
    build: ./srcdb

    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%' 
    ports:
        - 3306:3306  